/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicanomina;

/**
 *
 * @author OMAR
 */
public class Dialog extends javax.swing.JDialog {
    validaciones validar=new validaciones();

    /**
     * Creates new form Dialog
     */
    private final Lista lista =(Lista)this.getParent();
    
    public Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        validar.SoloNumeros(sueldo);
        validar.SoloLetras(nombre);
        validar.SoloLetras(puesto);
        validar.longitud(sueldo, 8);
    }

    Dialog(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        labelPuesto = new javax.swing.JLabel();
        labelSueldo = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        puesto = new javax.swing.JTextField();
        sueldo = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        labelNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelNombre.setText("Nombre:");
        getContentPane().add(labelNombre);
        labelNombre.setBounds(20, 50, 100, 30);

        labelPuesto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelPuesto.setText("Puesto:");
        getContentPane().add(labelPuesto);
        labelPuesto.setBounds(20, 100, 60, 30);

        labelSueldo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelSueldo.setText("Sueldo:");
        getContentPane().add(labelSueldo);
        labelSueldo.setBounds(20, 150, 50, 30);

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre);
        nombre.setBounds(90, 50, 200, 40);
        getContentPane().add(puesto);
        puesto.setBounds(90, 100, 200, 40);

        sueldo.setText("$");
        getContentPane().add(sueldo);
        sueldo.setBounds(90, 150, 150, 40);

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(40, 230, 100, 40);

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(230, 240, 73, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\OMAR\\Desktop\\imagenes\\fondofo.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if(nombre.getText().equals("")){
            javax.swing.JOptionPane.showMessageDialog(null,"introducir un nombre");
        }
        else if(puesto.getText().equals("")){
            javax.swing.JOptionPane.showMessageDialog(null,"introducir un puesto");
        }
        else if(sueldo.getText().equals("") || sueldo.getText().equals(".")){
            javax.swing.JOptionPane.showMessageDialog(null," introducir un sueldo valido");
        }
        else{
            arbol arbolito = new arbol(nombre.getText(),puesto.getText(),Double.parseDouble(sueldo.getText()));
            this.setVisible(false);
            lista.setVisible(true);
            lista.anadir(arbolito);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialog dialog = new Dialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPuesto;
    private javax.swing.JLabel labelSueldo;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField puesto;
    private javax.swing.JTextField sueldo;
    // End of variables declaration//GEN-END:variables
}
